### ISSUE TITLE
Create opentelemetry-shell-action

### ISSUE THREAD

**Issue by krzko** [krzko/opentelemetry-shell#42]
#### Is your feature request related to a problem?

To allow for seamless tracing to take place it would be nice to allow traces to take place behind the scenes, without too much user interaction ala the Jenkins OTEL plugin.

#### Describe the solution you'd like

```yaml
name: otel-sh-action-example
on: [push]
jobs:
  awesome-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krzko/opentelemetry-shell-action@v1
        with:
          otlp-exporter-otel-endpoint: 'https://otel.awesomedomain.com:443'
      - run: docker ...
      - run: gcloud ...
```

#### Describe alternatives you've considered

-

#### Additional context

-
